apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:sXPpxYBhGTw=,iv:I9Bp3uDYqUGlhUIya0R1Wo1wmTbpgSUt4cVTudTQsMY=,tag:isLV+1mdnuvQ9O5RcFPd3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14tlm3umd3myxg5v7xn40ej4xkq6qya3jn6uqz9x6z6qcevd53dzsycw7et
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcStKSHpRalp5ZjVtMTVM
            UnFnUHI1bHFJTHdWSzhGNXBXeWpYL2RyRGlJCjhRcDVwZ3ArekRGVU42RGpjNEhs
            bWtUYTlVSGZnRE1CTGw5c2hsb2NkZ0kKLS0tIHdUQkV3K1IrVlRjNDU5R2kvOTNq
            UTVLV3VEQ2dEdVMyZlpNT0tHUzhvVmsKsHSVWMvC36Ec7jbrHMNweL0ottOio11n
            Fac3dva8ywdjjsKOajg1jGyXvCdqerOFmMyOT5p3RuC8adZG6ZUQsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-09T20:35:56Z"
    mac: ENC[AES256_GCM,data:Dkdc9I/0amOpERpGICebarjCifwgWZ1frx6PxkyY9OvpXaGwjKYGfvOl3myFxHoBh8PSfXgeGand8EuD04Kk6aXyjDsoxUtSa+oxNiY+xgHBIOBbzl+0sZr7wcRNBMX6zEPwNzHr7PHg1ZdujE/u0zzQZr61LGogZiZU6girHzA=,iv:IqBiQj5INY2pU0ghb5hzxV5kObTzuI+v0o8zj8PRbUE=,tag:RyXmATvmRjNw/1aqr6x88Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
