apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgANaz+loZP4IuqOwSZh9jqCAqBdhNntTPXRfSoDsDenxmaYt/9JHBHYbsYWaS+PABgJn8yiXyDAOWzDF795mwHE13Af2GtbLh6435APoysuB177ESlx6hVbFS7Gc/DSoYy/zgI2LROw1jNwgcMhNUf8HtdNZ/iFxT/sZQyD9Ff/FA+sT5skupWTKh6n/lxPVQqEt318xWFxStyqpOpCPKFWJkcGpnsfKUHDsPKwsA/7YmB6LbtDl/QNxv8kAVaTwQ/ly19cl+36guh52T0vic2E+Q+NrWHKFDmUzAnU1M3U9QoPuhB9+2WhohgCYh5y4dZNmkIkGhf5CYqgf2vwzz54MPv0fNwqbbCdCLo2OC9EAAWLQGmwwmU8fRSOZgXu0lAg47ckStw6XEMTcg8LsZIFUlf5qMB939CsYABO9A79UD6s+kv7qE0GyxfzkP1uaLAjF1AOHYblFlwipSZQHto4hmUKXahoGUz2zbxgZu+3Yj/EwArceLjUBoI6EPyWSn8Gkr+5NiLKGRzVA23xvpuP5VrBjNsLElcYd/0sWq6gg1bohqjnpaAxJzHz4pfomw/maiVIp0TjXQlehkL5tNgmSDOTJAKEup7Sz03hrDP3IfLsP6eEA0eWuI/ewYny/rs0rcHlB8bIRQAPdljhRVZ1Z7ZFRLWW078yu5ZHYCXqwbeX8T+mNav1gACBXcpFUXyAlHg=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
status: {}
